### PR TITLE
Make configuration scripts equally compatible with Python 2 & 3

### PR DESCRIPTION
**Pull request by simonjwright**
In some Python-related parts of `aclocal.m4`, the form `print "foo"` is used, which is no longer allowed in Python 3. Changed to `print ("foo")`, which is compatible with Python 2.

I’ve regenerated `configure` using Autoconf 2.57, the previous version used 2.63.

`hooks.py` created (Ada source) files using `"wb"`; Python 3 doesn’t allow you to write strings to such a file, it has to be opened `"w"`. I’d have expected this to have been the proper mode all along?

  * aclocal.m4: In Python 2, 'print's parameters can be enclosed in
      parens; in Python 3, they must be.
  * configure: regenerated.
  * kernel/src/hooks.py: in Python 3, it's not possible to write
      strings to a binary file.

### CODE REVIEW

**Comment by simonjwright** [comment]
Related to #98

**Comment by setton** [comment]
Hello @simonjwright and thank you for the patch! We have a patch to hooks.py in the pipeline already but not for aclocal.m4 - for convenience, I will push a change after yours (also regenerate configure on our reference machine so as to minimise the diff and make sure it works on our older platforms.

**Comment by simonjwright** [comment]
@setton, that’s fine.

**Comment by setton** [comment]
@simonjwright I've pulled your changes under 1b9f0afb0f8a1db3c2e8cf61cfcfc05e84a8dae2. I applied some modifications:
  - `hooks.py` had already been fixed in the meantime
  - I regenerated `configure` with our version of the autotools, to minimise the diff

Thank you for the PR, this is appreciated.

**Pull request closed without merging**
